### ISSUE TITLE
borks ./tmp by default

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/csvkiller#14]
```console
$ csvkiller -V
0.2.4
$ mkdir tmp
$ touch tmp/precious.txt
$ csvkiller -c column1 -o test_csv test.csv
Creating worker for /home/myuser/test.csv
Worker closed (/home/myuser/test.csv) code 0
$ ls tmp
ls: cannot access tmp: No such file or directory
```

`./tmp` should not be the default - csvkiller should create a new dir inside of `os.tmpdir`

(and if the user provides `--tmp-directory`, csvkiller should also create a new dir inside of it... it should not delete it ... but see #13)

**Comment by summer4096** [comment]
https://github.com/faradayio/csvkiller/blob/master/index.js#L43
